
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpdGVzdGluZW4iLCJpZCI6IjVhOTU3ZDUxOTFmYTY3MGI5YTg1YTFiYiIsImlhdCI6MTUxOTc0OTM4NH0.qixrS4ppamonFHpcmgGjncCTmJqwmATIR-R-IZByY1I

{
    "title": "testiblogiiiii",
    "author": "testinen",
    "url": "ei oleeeeeeeeeeee",
    "likes": 10,
    "userId": "5a957d5191fa670b9a85a1bb"
}